{
  imports = [
    ./ai.nix
    ./nix.nix
    ./boot.nix
    ./gitea.nix
    ./music.nix
    ./nginx.nix
    ./users.nix
    ./gaming.nix
    ./flatpak.nix
    ./dnscrypt.nix
    ./programs.nix
    ./security.nix
    ./services.nix
    ./swayland.nix
    ./mailserver.nix
    ./networking.nix
    ./environment.nix
  ];
}
